CREATE TABLE IF NOT EXISTS `client_requirement` (
  `id` bigint(20) NOT NULL,
  `client_id` bigint(20) NOT NULL,
  `min_price` int(11) DEFAULT NULL,
  `max_price` int(11) DEFAULT NULL,
  `penthouse` tinyint(1) DEFAULT NULL,
  `car_parking_count_str` varchar(255) DEFAULT NULL,
  `storageroom_count_str` varchar(255) DEFAULT NULL,
  `bedroom_count_str` varchar(255) DEFAULT NULL,
  `bathroom_count_str` varchar(255) DEFAULT NULL,
  `courtyard_count_str` varchar(255) DEFAULT NULL,
  `enclosed_baclony_count_str` varchar(255) DEFAULT NULL,
  `studyroom_count_str` varchar(255) DEFAULT NULL,
  `courtyard_count_str` varchar(255) DEFAULT NULL,
  `floorplan_type_str` varchar(255) DEFAULT NULL,
  `min_total_size`  double DEFAULT NULL,
  `max_total_size`  double DEFAULT NULL,
  `is_split` tinyint(1) DEFAULT NULL,
  `is_studio` tinyint(1) DEFAULT NULL,
  `orientation_str` varchar(255) DEFAULT NULL,
  `ready_house` tinyint(1) DEFAULT NULL,
  `suburb_id` bigint(20) DEFAULT NULL,
  `distance_to_city`  double DEFAULT NULL,
  `universities` tinyint(1) DEFAULT NULL,
  `schools` tinyint(1) DEFAULT NULL,
  `shopping_center` tinyint(1) DEFAULT NULL,
  `train` tinyint(1) DEFAULT NULL,
  `chineseCommunity` tinyint(1) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `creation_date` datetime NOT NULL,
  `last_modified_date` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_client_id` (`client_id`),
  CONSTRAINT `fk_client_id` FOREIGN KEY (`client_id`) REFERENCES `client` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;