TRUNCATE TABLE id_generator;

INSERT INTO id_generator (id,gen_name) VALUES(1,'department');
INSERT INTO id_generator (id,gen_name) VALUES(2,'role');
INSERT INTO id_generator (id,gen_name) VALUES(3,'rolePermission');
INSERT INTO id_generator (id,gen_name) VALUES(4,'profile');
INSERT INTO id_generator (id,gen_name) VALUES(5,'profileDepartment');
INSERT INTO id_generator (id,gen_name) VALUES(6,'profileRole');
INSERT INTO id_generator (id,gen_name) VALUES(7,'permission');
INSERT INTO id_generator (id,gen_name) VALUES(8,'comment');
INSERT INTO id_generator (id,gen_name) VALUES(9,'area');
INSERT INTO id_generator (id,gen_name) VALUES(10,'areaComment');
INSERT INTO id_generator (id,gen_name) VALUES(11,'areaPolyline');
INSERT INTO id_generator (id,gen_name) VALUES(12,'suburb');
INSERT INTO id_generator (id,gen_name) VALUES(13,'suburbComment');
INSERT INTO id_generator (id,gen_name) VALUES(14,'suburbPolyline');
INSERT INTO id_generator (id,gen_name) VALUES(15,'project');
INSERT INTO id_generator (id,gen_name) VALUES(16,'projectComment');
INSERT INTO id_generator (id,gen_name) VALUES(17,'stage');
INSERT INTO id_generator (id,gen_name) VALUES(18,'stageComment');
INSERT INTO id_generator (id,gen_name) VALUES(19,'building');
INSERT INTO id_generator (id,gen_name) VALUES(20,'buildingComment');
INSERT INTO id_generator (id,gen_name) VALUES(21,'floorplan');
INSERT INTO id_generator (id,gen_name) VALUES(22,'floorplanComment');
INSERT INTO id_generator (id,gen_name) VALUES(23,'apartment');
INSERT INTO id_generator (id,gen_name) VALUES(24,'apartmentComment');
INSERT INTO id_generator (id,gen_name) VALUES(25,'media');
INSERT INTO id_generator (id,gen_name) VALUES(26,'projectMedia');